packages:
  - 'libs/*'
  - 'apps/*'
minimumReleaseAge: 1440 # Delay installing a newly published version of a package for 1440 minutes (1 day)
overrides:
  fast-uri@<=3.1.0: '>=3.1.1'
  fast-uri@<=3.1.1: '>=3.1.2'
  postcss@<8.5.10: '>=8.5.10'
