import { AdditionalQuestionsForm } from '../../types'

const mockPanels = [
  {
    addons: [],
    allowCalculateOverride: false,
    allowMultipleMasks: false,
    attributes: {},
    autofocus: false,
    breadcrumb: 'default',
    calculateServer: false,
    calculateValue: '',
    clearOnHide: false,
    conditional: {
      eq: '',
      show: null,
      when: null,
    },
    customClass: '',
    customDefaultValue: '',
    dataGridLabel: false,
    dbIndex: false,
    defaultValue: null,
    description: '',
    disabled: false,
    encrypted: false,
    errorLabel: '',
    hidden: false,
    hideLabel: false,
    id: 'er2mpjq',
    input: false,
    key: 'page1',
    label: 'Page 1',
    labelPosition: 'top',
    lazyLoad: false,
    modalEdit: false,
    multiple: false,
    overlay: {
      height: '',
      left: '',
      style: '',
      top: '',
      width: '',
    },
    persistent: false,
    placeholder: '',
    prefix: '',
    properties: {},
    protected: false,
    redrawOn: '',
    refreshOn: '',
    showCharCount: false,
    showWordCount: false,
    suffix: '',
    tabindex: '',
    tableView: false,
    theme: 'default',
    title: 'Page 1',
    tooltip: '',
    tree: false,
    type: 'panel',
    unique: false,
    validate: {
      custom: '',
      customPrivate: false,
      multiple: false,
      required: false,
      strictDateValidation: false,
      unique: false,
    },
    validateOn: 'change',
    widget: null,
  },
  {
    addons: [],
    allowCalculateOverride: false,
    allowMultipleMasks: false,
    attributes: {},
    autofocus: false,
    breadcrumb: 'default',
    calculateServer: false,
    calculateValue: '',
    clearOnHide: false,
    conditional: {
      eq: '',
      show: null,
      when: null,
    },
    customClass: '',
    customDefaultValue: '',
    dataGridLabel: false,
    dbIndex: false,
    defaultValue: null,
    description: '',
    disabled: false,
    encrypted: false,
    errorLabel: '',
    hidden: false,
    hideLabel: false,
    id: 'ehqvlem',
    input: false,
    key: 'page2',
    label: 'Page 2',
    labelPosition: 'top',
    lazyLoad: false,
    modalEdit: false,
    multiple: false,
    overlay: {
      height: '',
      left: '',
      style: '',
      top: '',
      width: '',
    },
    persistent: false,
    placeholder: '',
    prefix: '',
    properties: {},
    protected: false,
    redrawOn: '',
    refreshOn: '',
    showCharCount: false,
    showWordCount: false,
    suffix: '',
    tabindex: '',
    tableView: false,
    theme: 'default',
    title: 'Page 2',
    tooltip: '',
    tree: false,
    type: 'panel',
    unique: false,
    validate: {
      custom: '',
      customPrivate: false,
      multiple: false,
      required: false,
      strictDateValidation: false,
      unique: false,
    },
    validateOn: 'change',
    widget: null,
  },
]

const mockTextFields = [
  {
    addons: [],
    allowCalculateOverride: false,
    allowMultipleMasks: false,
    attributes: {},
    autofocus: false,
    calculateServer: false,
    calculateValue: '',
    clearOnHide: true,
    conditional: {
      eq: '',
      show: null,
      when: null,
    },
    customClass: '',
    customDefaultValue: '',
    dataGridLabel: false,
    dbIndex: false,
    defaultValue: null,
    description: '',
    disabled: false,
    displayMask: '',
    encrypted: false,
    errorLabel: '',
    hidden: false,
    hideLabel: false,
    id: 'emw2bm8',
    input: true,
    inputFormat: 'plain',
    inputMask: '',
    inputType: 'text',
    key: 'textField1',
    label: 'Text Field',
    labelPosition: 'top',
    mask: false,
    modalEdit: false,
    multiple: false,
    overlay: {
      height: '',
      left: '',
      style: '',
      top: '',
      width: '',
    },
    persistent: true,
    placeholder: '',
    position: 1,
    prefix: '',
    properties: {},
    protected: false,
    question: 53,
    redrawOn: '',
    refreshOn: '',
    showCharCount: false,
    showWordCount: false,
    spellcheck: true,
    suffix: '',
    tabindex: '',
    tableView: true,
    tooltip: '',
    truncateMultipleSpaces: false,
    type: 'textfield',
    unique: false,
    validate: {
      custom: '',
      customPrivate: false,
      json: null,
      maxLength: '',
      minLength: '',
      multiple: false,
      pattern: '',
      required: false,
      strictDateValidation: false,
      unique: false,
    },
    validateOn: 'change',
    widget: {
      type: 'input',
    },
  },
  {
    addons: [],
    allowCalculateOverride: false,
    allowMultipleMasks: false,
    attributes: {},
    autofocus: false,
    calculateServer: false,
    calculateValue: '',
    clearOnHide: true,
    conditional: {
      eq: '',
      show: null,
      when: null,
    },
    customClass: '',
    customDefaultValue: '',
    dataGridLabel: false,
    dbIndex: false,
    defaultValue: null,
    description: 'Description',
    disabled: false,
    displayMask: '',
    encrypted: false,
    errorLabel: '',
    hidden: false,
    hideLabel: false,
    id: 'et6zs29',
    input: true,
    inputFormat: 'plain',
    inputMask: '',
    inputType: 'text',
    key: 'textField2',
    label: 'Text Field',
    labelPosition: 'top',
    mask: false,
    modalEdit: false,
    multiple: false,
    overlay: {
      height: '',
      left: '',
      style: '',
      top: '',
      width: '',
    },
    persistent: true,
    placeholder: '',
    prefix: '',
    properties: {},
    protected: false,
    redrawOn: '',
    refreshOn: '',
    showCharCount: false,
    showWordCount: false,
    spellcheck: true,
    suffix: '',
    tabindex: '',
    tableView: true,
    tooltip: '',
    truncateMultipleSpaces: false,
    type: 'textfield',
    unique: false,
    validate: {
      custom: '',
      customPrivate: false,
      json: {
        '==': [
          {
            var: 'text',
          },
          'Bob',
        ],
      },
      maxLength: '',
      minLength: '',
      multiple: false,
      pattern: '',
      required: true,
      strictDateValidation: false,
      unique: false,
    },
    validateOn: 'change',
    widget: {
      type: 'input',
    },
  },
]

const mockTextAreas = [
  {
    addons: [],
    allowCalculateOverride: false,
    allowMultipleMasks: false,
    attributes: {},
    autoExpand: false,
    autofocus: false,
    calculateServer: false,
    calculateValue: '',
    clearOnHide: true,
    conditional: {
      eq: '',
      show: null,
      when: null,
    },
    customClass: '',
    customDefaultValue: '',
    dataGridLabel: false,
    dbIndex: false,
    defaultValue: null,
    description: '',
    disabled: false,
    displayMask: '',
    editor: '',
    encrypted: false,
    errorLabel: '',
    fixedSize: true,
    hidden: false,
    hideLabel: false,
    id: 'erhvzak',
    input: true,
    inputFormat: 'html',
    inputMask: '',
    inputType: 'text',
    key: 'textArea1',
    label: 'Text Area',
    labelPosition: 'top',
    mask: false,
    maxCharCount: null,
    modalEdit: false,
    multiple: false,
    overlay: {
      height: '',
      left: '',
      style: '',
      top: '',
      width: '',
    },
    persistent: true,
    placeholder: '',
    position: 2,
    prefix: '',
    properties: {},
    protected: false,
    question: 54,
    redrawOn: '',
    refreshOn: '',
    rows: 3,
    showCharCount: false,
    showWordCount: false,
    spellcheck: true,
    suffix: '',
    tabindex: '',
    tableView: true,
    tooltip: '',
    truncateMultipleSpaces: false,
    type: 'textarea',
    unique: false,
    validate: {
      custom: '',
      customPrivate: false,
      json: null,
      maxLength: '',
      maxWords: '',
      minLength: '',
      minWords: '',
      multiple: false,
      pattern: '',
      required: false,
      strictDateValidation: false,
      unique: false,
    },
    validateOn: 'change',
    widget: {
      type: 'input',
    },
    wysiwyg: false,
  },
  {
    addons: [],
    allowCalculateOverride: false,
    allowMultipleMasks: false,
    attributes: {},
    autoExpand: true,
    autofocus: false,
    calculateServer: false,
    calculateValue: '',
    clearOnHide: true,
    conditional: {
      eq: '',
      show: null,
      when: null,
    },
    customClass: '',
    customDefaultValue: '',
    dataGridLabel: false,
    dbIndex: false,
    defaultValue: null,
    description: 'Description',
    disabled: false,
    displayMask: '',
    editor: '',
    encrypted: false,
    errorLabel: '',
    fixedSize: true,
    hidden: false,
    hideLabel: false,
    id: 'ewrg6od',
    input: true,
    inputFormat: 'html',
    inputMask: '',
    inputType: 'text',
    key: 'textArea2',
    label: 'Text Area',
    labelPosition: 'top',
    mask: false,
    maxCharCount: '80',
    modalEdit: false,
    multiple: false,
    overlay: {
      height: '',
      left: '',
      style: '',
      top: '',
      width: '',
    },
    persistent: true,
    placeholder: '',
    prefix: '',
    properties: {},
    protected: false,
    redrawOn: '',
    refreshOn: '',
    rows: 3,
    showCharCount: false,
    showWordCount: false,
    spellcheck: true,
    suffix: '',
    tabindex: '',
    tableView: true,
    tooltip: '',
    truncateMultipleSpaces: false,
    type: 'textarea',
    unique: false,
    validate: {
      custom: '',
      customPrivate: false,
      json: {
        '==': [
          {
            var: 'text',
          },
          'Bob',
        ],
      },
      maxLength: '',
      maxWords: '',
      minLength: '',
      minWords: '',
      multiple: false,
      pattern: '',
      required: true,
      strictDateValidation: false,
      unique: false,
    },
    validateOn: 'change',
    widget: {
      type: 'input',
    },
    wysiwyg: false,
  },
]

const mockSelectBoxes = [
  {
    addons: [],
    allowCalculateOverride: false,
    allowMultipleMasks: false,
    attributes: {},
    authenticate: false,
    autofocus: false,
    calculateServer: false,
    calculateValue: '',
    clearOnHide: true,
    conditional: {
      eq: '',
      show: null,
      when: null,
    },
    customClass: '',
    customDefaultValue: '',
    data: {
      url: '',
    },
    dataGridLabel: false,
    dataSrc: 'values',
    dbIndex: false,
    defaultValue: null,
    description: '',
    disabled: false,
    encrypted: false,
    errorLabel: '',
    fieldSet: false,
    hidden: false,
    hideLabel: false,
    id: 'e7rvihg',
    ignoreCache: false,
    inline: false,
    input: true,
    inputType: 'checkbox',
    key: 'selectBoxes',
    label: 'Select Boxes',
    labelPosition: 'top',
    modalEdit: false,
    multiple: false,
    overlay: {
      height: '',
      left: '',
      style: '',
      top: '',
      width: '',
    },
    persistent: true,
    placeholder: '',
    position: 3,
    prefix: '',
    properties: {},
    protected: false,
    question: 55,
    redrawOn: '',
    refreshOn: '',
    showCharCount: false,
    showWordCount: false,
    suffix: '',
    tabindex: '',
    tableView: false,
    template: '<span>{{ item.label }}</span>',
    tooltip: '',
    type: 'selectboxes',
    unique: false,
    validate: {
      custom: '',
      customPrivate: false,
      json: null,
      multiple: false,
      onlyAvailableItems: false,
      required: false,
      strictDateValidation: false,
      unique: false,
    },
    validateOn: 'change',
    values: [
      {
        label: 'One',
        position: 1,
        value: 'one',
      },
      {
        label: 'Two',
        position: 2,
        value: 'two',
      },
    ],
    widget: null,
  },
  {
    addons: [],
    allowCalculateOverride: false,
    allowMultipleMasks: false,
    attributes: {},
    authenticate: false,
    autofocus: false,
    calculateServer: false,
    calculateValue: '',
    clearOnHide: true,
    conditional: {
      eq: '',
      show: null,
      when: null,
    },
    customClass: '',
    customDefaultValue: '',
    data: {
      url: '',
    },
    dataGridLabel: false,
    dataSrc: 'values',
    dbIndex: false,
    defaultValue: null,
    description: 'Description',
    disabled: false,
    encrypted: false,
    errorLabel: '',
    fieldSet: false,
    hidden: false,
    hideLabel: false,
    id: 'e577fo9',
    ignoreCache: false,
    inline: false,
    input: true,
    inputType: 'checkbox',
    key: 'selectBoxes1',
    label: 'Select Boxes',
    labelPosition: 'top',
    modalEdit: false,
    multiple: false,
    overlay: {
      height: '',
      left: '',
      style: '',
      top: '',
      width: '',
    },
    persistent: true,
    placeholder: '',
    prefix: '',
    properties: {},
    protected: false,
    redrawOn: '',
    refreshOn: '',
    showCharCount: false,
    showWordCount: false,
    suffix: '',
    tabindex: '',
    tableView: false,
    template: '<span>{{ item.label }}</span>',
    tooltip: '',
    type: 'selectboxes',
    unique: false,
    validate: {
      custom: '',
      customPrivate: false,
      json: {
        '==': [
          {
            var: 'text',
          },
          'Bob',
        ],
      },
      multiple: false,
      onlyAvailableItems: false,
      required: true,
      strictDateValidation: false,
      unique: false,
    },
    validateOn: 'change',
    values: [
      {
        label: 'One',
        value: 'one',
      },
      {
        label: 'Two',
        value: 'two',
      },
    ],
    widget: null,
  },
]

const mockSelects = [
  {
    addons: [],
    allowCalculateOverride: false,
    allowMultipleMasks: false,
    attributes: {},
    authenticate: false,
    autofocus: false,
    calculateServer: false,
    calculateValue: '',
    clearOnHide: true,
    clearOnRefresh: false,
    conditional: {
      eq: '',
      show: null,
      when: null,
    },
    customClass: '',
    customDefaultValue: '',
    customOptions: {},
    data: {
      custom: '',
      json: '',
      resource: '',
      url: '',
      values: [
        {
          label: 'One',
          value: 'one',
        },
        {
          label: 'Two',
          value: 'two',
        },
      ],
    },
    dataGridLabel: false,
    dataSrc: 'values',
    dbIndex: false,
    defaultValue: null,
    description: '',
    disabled: false,
    encrypted: false,
    errorLabel: '',
    filter: '',
    fuseOptions: {
      include: 'score',
      threshold: 0.3,
    },
    hidden: false,
    hideLabel: false,
    id: 'e33dqt',
    idPath: 'id',
    ignoreCache: false,
    indexeddb: {
      filter: {},
    },
    input: true,
    key: 'select',
    label: 'Select',
    labelPosition: 'top',
    lazyLoad: true,
    limit: 100,
    minSearch: 0,
    modalEdit: false,
    multiple: false,
    overlay: {
      height: '',
      left: '',
      style: '',
      top: '',
      width: '',
    },
    persistent: true,
    placeholder: '',
    prefix: '',
    properties: {},
    protected: false,
    readOnlyValue: false,
    redrawOn: '',
    refreshOn: '',
    searchDebounce: 0.3,
    searchEnabled: true,
    searchField: '',
    selectFields: '',
    selectThreshold: 0.3,
    showCharCount: false,
    showWordCount: false,
    suffix: '',
    tabindex: '',
    tableView: true,
    template: '<span>{{ item.label }}</span>',
    tooltip: '',
    type: 'select',
    unique: false,
    uniqueOptions: false,
    useExactSearch: false,
    validate: {
      custom: '',
      customPrivate: false,
      json: '',
      multiple: false,
      onlyAvailableItems: false,
      required: false,
      strictDateValidation: false,
      unique: false,
    },
    validateOn: 'change',
    valueProperty: '',
    widget: 'html5',
  },
  {
    addons: [],
    allowCalculateOverride: false,
    allowMultipleMasks: false,
    attributes: {},
    authenticate: false,
    autofocus: false,
    calculateServer: false,
    calculateValue: '',
    clearOnHide: true,
    clearOnRefresh: false,
    conditional: {
      eq: '',
      show: null,
      when: null,
    },
    customClass: '',
    customDefaultValue: '',
    customOptions: {},
    data: {
      custom: '',
      json: '',
      resource: '',
      url: '',
      values: [
        {
          label: 'One',
          value: 'one',
        },
        {
          label: 'Two',
          value: 'two',
        },
      ],
    },
    dataGridLabel: false,
    dataSrc: 'values',
    dbIndex: false,
    defaultValue: null,
    description: 'Description',
    disabled: false,
    encrypted: false,
    errorLabel: '',
    filter: '',
    fuseOptions: {
      include: 'score',
      threshold: 0.3,
    },
    hidden: false,
    hideLabel: false,
    id: 'e4p4x3ea',
    idPath: 'id',
    ignoreCache: false,
    indexeddb: {
      filter: {},
    },
    input: true,
    key: 'select1',
    label: 'Select',
    labelPosition: 'top',
    lazyLoad: true,
    limit: 100,
    minSearch: 0,
    modalEdit: false,
    multiple: false,
    overlay: {
      height: '',
      left: '',
      style: '',
      top: '',
      width: '',
    },
    persistent: true,
    placeholder: 'Placeholder',
    prefix: '',
    properties: {},
    protected: false,
    readOnlyValue: false,
    redrawOn: '',
    refreshOn: '',
    searchDebounce: 0.3,
    searchEnabled: true,
    searchField: '',
    selectFields: '',
    selectThreshold: 0.3,
    showCharCount: false,
    showWordCount: false,
    suffix: '',
    tabindex: '',
    tableView: true,
    template: '<span>{{ item.label }}</span>',
    tooltip: '',
    type: 'select',
    unique: false,
    uniqueOptions: false,
    useExactSearch: false,
    validate: {
      custom: '',
      customPrivate: false,
      json: {
        '==': [
          {
            var: 'text',
          },
          'Bob',
        ],
      },
      multiple: false,
      onlyAvailableItems: false,
      required: true,
      strictDateValidation: false,
      unique: false,
    },
    validateOn: 'change',
    valueProperty: '',
    widget: 'html5',
  },
]

const mockRadios = [
  {
    addons: [],
    allowCalculateOverride: false,
    allowMultipleMasks: false,
    attributes: {},
    authenticate: false,
    autofocus: false,
    calculateServer: false,
    calculateValue: '',
    clearOnHide: true,
    conditional: {
      eq: '',
      show: null,
      when: null,
    },
    customClass: '',
    customDefaultValue: '',
    data: {
      url: '',
    },
    dataGridLabel: false,
    dataSrc: 'values',
    dbIndex: false,
    defaultValue: null,
    description: '',
    disabled: false,
    encrypted: false,
    errorLabel: '',
    fieldSet: false,
    hidden: false,
    hideLabel: false,
    id: 'e44f4c',
    ignoreCache: false,
    input: true,
    inputType: 'radio',
    key: 'radio',
    label: 'Radio',
    labelPosition: 'top',
    modalEdit: false,
    multiple: false,
    overlay: {
      height: '',
      left: '',
      style: '',
      top: '',
      width: '',
    },
    persistent: true,
    placeholder: '',
    prefix: '',
    properties: {},
    protected: false,
    redrawOn: '',
    refreshOn: '',
    showCharCount: false,
    showWordCount: false,
    suffix: '',
    tabindex: '',
    tableView: false,
    template: '<span>{{ item.label }}</span>',
    tooltip: '',
    type: 'radio',
    unique: false,
    validate: {
      custom: '',
      customPrivate: false,
      json: '',
      multiple: false,
      onlyAvailableItems: false,
      required: false,
      strictDateValidation: false,
      unique: false,
    },
    validateOn: 'change',
    values: [
      {
        label: 'One',
        value: 'one',
      },
      {
        label: 'Two',
        value: 'two',
      },
    ],
    widget: null,
  },
  {
    addons: [],
    allowCalculateOverride: false,
    allowMultipleMasks: false,
    attributes: {},
    authenticate: false,
    autofocus: false,
    calculateServer: false,
    calculateValue: '',
    clearOnHide: true,
    conditional: {
      eq: '',
      show: null,
      when: null,
    },
    customClass: '',
    customDefaultValue: '',
    data: {
      url: '',
    },
    dataGridLabel: false,
    dataSrc: 'values',
    dbIndex: false,
    defaultValue: null,
    description: 'Description',
    disabled: false,
    encrypted: false,
    errorLabel: '',
    fieldSet: false,
    hidden: false,
    hideLabel: false,
    id: 'ej0tb08',
    ignoreCache: false,
    input: true,
    inputType: 'radio',
    key: 'radio1',
    label: 'Radio',
    labelPosition: 'top',
    modalEdit: false,
    multiple: false,
    overlay: {
      height: '',
      left: '',
      style: '',
      top: '',
      width: '',
    },
    persistent: true,
    placeholder: '',
    prefix: '',
    properties: {},
    protected: false,
    redrawOn: '',
    refreshOn: '',
    showCharCount: false,
    showWordCount: false,
    suffix: '',
    tabindex: '',
    tableView: false,
    template: '<span>{{ item.label }}</span>',
    tooltip: '',
    type: 'radio',
    unique: false,
    validate: {
      custom: '',
      customPrivate: false,
      json: {
        '==': [
          {
            var: 'text',
          },
          'Bob',
        ],
      },
      multiple: false,
      onlyAvailableItems: false,
      required: true,
      strictDateValidation: false,
      unique: false,
    },
    validateOn: 'change',
    values: [
      {
        label: 'One',
        value: 'one',
      },
      {
        label: 'Two',
        value: 'two',
      },
    ],
    widget: null,
  },
]

const mockTime = [
  {
    conditional: {
      eq: '',
      show: null,
      when: null,
    },
    description: '',
    input: true,
    key: 'time',
    label: 'Time',
    type: 'time',
    validate: {
      custom: '',
      customPrivate: false,
      json: null,
      multiple: false,
      required: false,
      required_error_message: null,
      strictDateValidation: false,
      unique: false,
    },
  },
  {
    conditional: {
      eq: '',
      show: null,
      when: null,
    },
    description: '',
    input: true,
    key: 'time1',
    label: 'Time',
    type: 'time',
    validate: {
      custom: '',
      customPrivate: false,
      multiple: false,
      required: false,
      strictDateValidation: false,
      unique: false,
    },
  },
]

export const mockData: AdditionalQuestionsForm & { classification: string | null; id: number } = {
  classification: null,
  components: [
    {
      ...mockPanels[0],
      components: [mockTextFields[0], mockTextAreas[0], mockSelectBoxes[0], mockSelects[0], mockRadios[0], mockTime[0]],
      path: 'page1',
    },
    {
      ...mockPanels[1],
      components: [mockTextFields[1], mockTextAreas[1], mockSelectBoxes[1], mockSelects[1], mockRadios[1], mockTime[1]],
      path: 'page2',
    },
  ],
  display: 'wizard',
  id: 2,
  title: 'Test title',
}
